#Spring docs: https://docs.spring.io/spring-ai/reference/api/chat/google-genai-chat.html
spring:
  application:
    name: Gemini-Gen-AI
  ai:
    chat:
      memory:
        repository:
          jdbc:
#            this wil create a table: SPRING_AI_CHAT_MEMORY
            initialize-schema: always
    model:
      chat: google-genai
    google:
      genai:
        api-key: ${OPEN_AI_API_KEY}
        chat:
          options:
            model: gemini-2.0-flash #default
  datasource:
    url: '${DB_URL:jdbc:postgresql://localhost:15432/postgres}'
    username: '${DB_USERNAME:postgres}'
    password: '${DB_PASSWORD:postgres}'
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always